spring.application.name=SpringBootDemoProject

#configure server port
server.port=2026

#configure db props
spring.datasource.url=jdbc:mysql://localhost:3306/soadb5
spring.datasource.username=root
spring.datasource.password=root

#configure jpq and hibernate props
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect